// Generated by CoffeeScript 1.9.3
(function() {
  window.WIDTH = 84;

  window.HEIGHT = 120;

  window.DEPTH = 7;

  window.MATERIAL = new THREE.MeshDepthMaterial({
    side: THREE.DoubleSide
  });

}).call(this);
