// Generated by CoffeeScript 1.9.3
(function() {
  window.PixelGrid = (function() {
    function PixelGrid(content) {
      var bw, d, data, h, i, imageData, j, k, l, len, m, n, ref, ref1, ref2, ref3, w, x, y;
      imageData = content.getImageData(0, 0, content.canvas.width, content.canvas.height);
      data = imageData.data;
      bw = [];
      for (i = j = 0, len = data.length; j < len; i = ++j) {
        d = data[i];
        if (i % 4 === 3) {
          bw.push(d);
        }
      }
      w = WIDTH;
      h = HEIGHT;
      this.pixels = new Array(w);
      for (x = k = 0, ref = w; 0 <= ref ? k < ref : k > ref; x = 0 <= ref ? ++k : --k) {
        this.pixels[x] = [];
        for (y = l = 0, ref1 = h; 0 <= ref1 ? l < ref1 : l > ref1; y = 0 <= ref1 ? ++l : --l) {
          this.pixels[x].push(0);
        }
      }
      for (x = m = 0, ref2 = w; 0 <= ref2 ? m < ref2 : m > ref2; x = 0 <= ref2 ? ++m : --m) {
        for (y = n = 0, ref3 = h; 0 <= ref3 ? n < ref3 : n > ref3; y = 0 <= ref3 ? ++n : --n) {
          d = x + (w * h - w) - (y * w);
          this.pixels[x][y] = bw[d];
        }
      }
    }

    PixelGrid.prototype.getPixel = function(x, y) {
      if (this.pixels[x] && this.pixels[x][y]) {
        return this.pixels[x][y];
      } else {
        return 0;
      }
    };

    return PixelGrid;

  })();

}).call(this);
